Avoid two kinds of escaping in error strings
Fixes a regression from
https://github.com/regulaforensics/DocumentReader-web-python-client/pull/255,
where quotes in strings were escaped both with backslashes, and as html
escapes. Using both is redundant, and yields a SyntaxError / warning
when you try to run it on certain Python versions:

> SyntaxError: invalid escape sequence '\&'